# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'provisioning/vbox.rb'
VBoxUtils.check_version('7.0.14')
Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
    # Box and hostname settings
    config.vm.box = "debian/bookworm64"
    config.vm.box_version = "12.20231211.1"
    config.vm.box_check_update = false
    config.vm.hostname = "acr2324"

    # Network and port forwarding settings
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", type: "dhcp"
    config.vm.network "private_network", ip: "192.168.56.10", netmask: "255.255.255.0"

    # Synced folder
    config.vm.synced_folder "C:/Users/aaron/Documents/Q8/AISI/practica0/html", "/var/www/html", mount_options: ["dmode=755,fmode=644"]

    # Configure hostmanager and vbguest plugins
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.vbguest.auto_update = false

    # Provider-specific customizations (CPU, memory, disk...)
    config.vm.provider "virtualbox" do |vb|
	vb.name = "AISI-P0-#{config.vm.hostname}"
	vb.gui = false
	vb.cpus = 2
	vb.memory = 2048

	sasController = "SAS Controller"
	disk = "diskVM-SAS.vmdk"
	
	# Create the virtual disk if doesn't exist
	unless File.exist?(disk)
		vb.customize ["createmedium", "disk", "--filename", disk, "--format", "VMDK", "--size", 2048]
	end

	# Add storage SAS controller only when the VM is provisioned for the first time
	unless File.exist?(".vagrant/machines/default/virtualbox/action_provision")
		vb.customize ["storagectl", :id, "--name", sasController, "--add", "sas", "--portcount", 1]
	end

	# Attach the virtual disk into the storage SAS controller
	vb.customize ["storageattach", :id, "--storagectl", sasController, "--port", 0, "--device", 0, "--type", "hdd", "--medium", disk]
    end

    # Embedded provisioning through shell script
    config.vm.provision "shell", run: "once", inline: <<-SHELL
	apt update
	# Complete the following commands
	apt install -y apache2 php php-mysql
	systemctl start apache2
	systemctl enable apache2
	mkfs.ext4 /dev/sdb
	mkdir /mnt/acr2324
    SHELL
    
    # Provisioning through an external shell script
    config.vm.provision "shell", run: "always", path: "provisioning/script.sh", args: "acr2324"
end
