# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'provisioning/vbox.rb'
VBoxUtils.check_version('7.0.14')
Vagrant.require_version ">= 2.4.1"

Vagrant.configure("2") do |config|
    config.vm.box = "acr2324/jammy64"
    config.vm.hostname = "acr2324-ansible"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    # Configure hostmanager and vbguest plugins
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.vbguest.auto_update = false

    config.vm.provider "virtualbox" do |vb|
	vb.name = "AISI-P3-EJ2-#{config.vm.hostname}"
	vb.cpus = 1
	vb.memory = 1024
	vb.gui = false
    end

    config.vm.provision "ansible_local" do |ansible|
	ansible.install = "true"
	ansible.install_mode = "pip3"
	ansible.playbook = "provisioning/playbook.yml"
    end
end
